"""add_household_invite_and_admin

Revision ID: 881948f17938
Revises: 50cc28359ac9
Create Date: 2026-04-03 12:27:55.938722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881948f17938'
down_revision: Union[str, Sequence[str], None] = '50cc28359ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('invite_code', sa.String(length=10), nullable=False))
    op.add_column('households', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_households_invite_code'), 'households', ['invite_code'], unique=True)
    op.create_foreign_key(None, 'households', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'households', type_='foreignkey')
    op.drop_index(op.f('ix_households_invite_code'), table_name='households')
    op.drop_column('households', 'admin_id')
    op.drop_column('households', 'invite_code')
    # ### end Alembic commands ###
