"""add_household_invite_and_admin

Revision ID: 881948f17938
Revises: 8f6c4ade40b3
Create Date: 2026-04-03 12:27:55.938722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881948f17938'
down_revision: Union[str, Sequence[str], None] = '8f6c4ade40b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import secrets
    import string

    # Step 1: Add invite_code as nullable so existing rows don't fail immediately.
    op.add_column('households', sa.Column('invite_code', sa.String(length=10), nullable=True))
    op.add_column('households', sa.Column('admin_id', sa.UUID(), nullable=True))

    # Step 2: Backfill unique invite codes for every existing row.
    connection = op.get_bind()
    households = connection.execute(
        sa.text("SELECT id FROM households WHERE invite_code IS NULL")
    ).fetchall()
    # Seed used_codes with any codes already in the DB (e.g. from a partial run).
    existing = connection.execute(
        sa.text("SELECT invite_code FROM households WHERE invite_code IS NOT NULL")
    ).fetchall()
    used_codes: set = {row[0] for row in existing}
    for (household_id,) in households:
        while True:
            code = "".join(
                secrets.choice(string.ascii_uppercase + string.digits) for _ in range(6)
            )
            if code not in used_codes:
                used_codes.add(code)
                break
        connection.execute(
            sa.text("UPDATE households SET invite_code = :code WHERE id = :id"),
            {"code": code, "id": household_id},
        )

    # Step 3: Now that every row has a value, enforce NOT NULL.
    op.alter_column('households', 'invite_code', nullable=False)

    # Step 4: Create the unique index and the admin foreign key.
    op.create_index(op.f('ix_households_invite_code'), 'households', ['invite_code'], unique=True)
    op.create_foreign_key(None, 'households', 'users', ['admin_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'households', type_='foreignkey')
    op.drop_index(op.f('ix_households_invite_code'), table_name='households')
    op.drop_column('households', 'admin_id')
    op.drop_column('households', 'invite_code')
    # ### end Alembic commands ###
