"""add households

Revision ID: 8f6c4ade40b3
Revises: 9371dec11722
Create Date: 2026-04-03 06:59:20.245893

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f6c4ade40b3"
down_revision: str | Sequence[str] | None = "9371dec11722"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredients",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=True)
    op.create_table(
        "dish_ingredients",
        sa.Column("dish_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["dish_id"], ["dishes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dish_id", "ingredient_id"),
    )
    op.add_column("cooklogs", sa.Column("household_id", sa.UUID(), nullable=False))
    op.add_column("cooklogs", sa.Column("rating", sa.Integer(), nullable=True))
    op.alter_column(
        "cooklogs", "note", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.create_index(op.f("ix_cooklogs_household_id"), "cooklogs", ["household_id"], unique=False)
    op.create_foreign_key(
        None, "cooklogs", "households", ["household_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("dishes", sa.Column("dish_type", sa.String(length=50), nullable=False))
    op.add_column("dishes", sa.Column("meal_type", sa.String(length=50), nullable=False))
    op.add_column("dishes", sa.Column("spiciness", sa.Integer(), nullable=False))
    op.add_column("dishes", sa.Column("prep_time_minutes", sa.Integer(), nullable=True))
    op.add_column("dishes", sa.Column("calories_estimate", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("household_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_users_household_id"), "users", ["household_id"], unique=False)
    op.create_foreign_key(None, "users", "households", ["household_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_household_id"), table_name="users")
    op.drop_column("users", "household_id")
    op.drop_column("dishes", "calories_estimate")
    op.drop_column("dishes", "prep_time_minutes")
    op.drop_column("dishes", "spiciness")
    op.drop_column("dishes", "meal_type")
    op.drop_column("dishes", "dish_type")
    op.drop_constraint(None, "cooklogs", type_="foreignkey")
    op.drop_index(op.f("ix_cooklogs_household_id"), table_name="cooklogs")
    op.alter_column(
        "cooklogs", "note", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.drop_column("cooklogs", "rating")
    op.drop_column("cooklogs", "household_id")
    op.drop_table("dish_ingredients")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_table("households")
    # ### end Alembic commands ###
