"""Migration: Add note in cooklogs

Revision ID: 9371dec11722
Revises: 257bf1ddd4ec
Create Date: 2025-11-17 15:03:51.851893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9371dec11722'
down_revision: Union[str, Sequence[str], None] = '257bf1ddd4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooklogs', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cooklogs', 'note')
    # ### end Alembic commands ###
