"""Migration: Add note in cooklogs

Revision ID: 9371dec11722
Revises: 257bf1ddd4ec
Create Date: 2025-11-17 15:03:51.851893

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9371dec11722"
down_revision: str | Sequence[str] | None = "257bf1ddd4ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cooklogs", sa.Column("note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cooklogs", "note")
    # ### end Alembic commands ###
