"""add household specific dishes

Revision ID: d245e1560a95
Revises: 1a69f3328f29
Create Date: 2026-04-09 16:45:14.273926

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d245e1560a95"
down_revision: str | Sequence[str] | None = "1a69f3328f29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dishes", sa.Column("household_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("ix_dishes_name"), table_name="dishes")
    op.create_index(op.f("ix_dishes_name"), "dishes", ["name"], unique=False)
    op.create_index(op.f("ix_dishes_household_id"), "dishes", ["household_id"], unique=False)
    op.create_foreign_key(
        None, "dishes", "households", ["household_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dishes", type_="foreignkey")
    op.drop_index(op.f("ix_dishes_household_id"), table_name="dishes")
    op.drop_index(op.f("ix_dishes_name"), table_name="dishes")
    op.create_index(op.f("ix_dishes_name"), "dishes", ["name"], unique=True)
    op.drop_column("dishes", "household_id")
    # ### end Alembic commands ###
